import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer";
import styles from "./styles.module.css"
import NavBar from "@/components/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  console.log("Test")

  

  return (
    <html lang="ja">
      <body
        className={`antialiased`}
      >
        <NavBar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
